/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminAccessRouteImport } from './routes/super-admin-access'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActivationRouteImport } from './routes/activation'
import { Route as AccesRouteImport } from './routes/acces'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as SuiviTokenRouteImport } from './routes/suivi.$token'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as DemoStockRouteImport } from './routes/demo.stock'
import { Route as DemoReparationsRouteImport } from './routes/demo.reparations'
import { Route as DemoParuresRouteImport } from './routes/demo.parures'
import { Route as DemoPaiementsEnAttenteRouteImport } from './routes/demo.paiements-en-attente'
import { Route as DemoOrCasseRouteImport } from './routes/demo.or-casse'
import { Route as DemoJournalQuotidienRouteImport } from './routes/demo.journal-quotidien'
import { Route as DemoFournisseursRouteImport } from './routes/demo.fournisseurs'
import { Route as DemoFacturesRouteImport } from './routes/demo.factures'
import { Route as DemoDepensesRouteImport } from './routes/demo.depenses'
import { Route as DemoDashboardRouteImport } from './routes/demo.dashboard'
import { Route as DemoCoursOrRouteImport } from './routes/demo.cours-or'
import { Route as DemoClientsRouteImport } from './routes/demo.clients'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedReparationsRouteImport } from './routes/_authenticated/reparations'
import { Route as AuthenticatedParuresRouteImport } from './routes/_authenticated/parures'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedPaiementsEnAttenteRouteImport } from './routes/_authenticated/paiements-en-attente'
import { Route as AuthenticatedOrCasseRouteImport } from './routes/_authenticated/or-casse'
import { Route as AuthenticatedNouvelleVenteRouteImport } from './routes/_authenticated/nouvelle-vente'
import { Route as AuthenticatedJournalQuotidienRouteImport } from './routes/_authenticated/journal-quotidien'
import { Route as AuthenticatedFournisseursRouteImport } from './routes/_authenticated/fournisseurs'
import { Route as AuthenticatedFacturesRouteImport } from './routes/_authenticated/factures'
import { Route as AuthenticatedDepensesRouteImport } from './routes/_authenticated/depenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoursOrRouteImport } from './routes/_authenticated/cours-or'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedBoutiqueRouteImport } from './routes/_authenticated/boutique'
import { Route as AuthenticatedProduitIdRouteImport } from './routes/_authenticated/produit.$id'
import { Route as AuthenticatedFournisseursIdRouteImport } from './routes/_authenticated/fournisseurs_.$id'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients_.$id'
import { Route as ApiPublicHooksUpdateGoldPricesRouteImport } from './routes/api/public/hooks/update-gold-prices'

const SuperAdminAccessRoute = SuperAdminAccessRouteImport.update({
  id: '/super-admin-access',
  path: '/super-admin-access',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationRoute = ActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesRoute = AccesRouteImport.update({
  id: '/acces',
  path: '/acces',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const SuiviTokenRoute = SuiviTokenRouteImport.update({
  id: '/suivi/$token',
  path: '/suivi/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStockRoute = DemoStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => DemoRoute,
} as any)
const DemoReparationsRoute = DemoReparationsRouteImport.update({
  id: '/reparations',
  path: '/reparations',
  getParentRoute: () => DemoRoute,
} as any)
const DemoParuresRoute = DemoParuresRouteImport.update({
  id: '/parures',
  path: '/parures',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPaiementsEnAttenteRoute = DemoPaiementsEnAttenteRouteImport.update({
  id: '/paiements-en-attente',
  path: '/paiements-en-attente',
  getParentRoute: () => DemoRoute,
} as any)
const DemoOrCasseRoute = DemoOrCasseRouteImport.update({
  id: '/or-casse',
  path: '/or-casse',
  getParentRoute: () => DemoRoute,
} as any)
const DemoJournalQuotidienRoute = DemoJournalQuotidienRouteImport.update({
  id: '/journal-quotidien',
  path: '/journal-quotidien',
  getParentRoute: () => DemoRoute,
} as any)
const DemoFournisseursRoute = DemoFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => DemoRoute,
} as any)
const DemoFacturesRoute = DemoFacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => DemoRoute,
} as any)
const DemoDepensesRoute = DemoDepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => DemoRoute,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DemoRoute,
} as any)
const DemoCoursOrRoute = DemoCoursOrRouteImport.update({
  id: '/cours-or',
  path: '/cours-or',
  getParentRoute: () => DemoRoute,
} as any)
const DemoClientsRoute = DemoClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DemoRoute,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReparationsRoute =
  AuthenticatedReparationsRouteImport.update({
    id: '/reparations',
    path: '/reparations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParuresRoute = AuthenticatedParuresRouteImport.update({
  id: '/parures',
  path: '/parures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaiementsEnAttenteRoute =
  AuthenticatedPaiementsEnAttenteRouteImport.update({
    id: '/paiements-en-attente',
    path: '/paiements-en-attente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrCasseRoute = AuthenticatedOrCasseRouteImport.update({
  id: '/or-casse',
  path: '/or-casse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNouvelleVenteRoute =
  AuthenticatedNouvelleVenteRouteImport.update({
    id: '/nouvelle-vente',
    path: '/nouvelle-vente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJournalQuotidienRoute =
  AuthenticatedJournalQuotidienRouteImport.update({
    id: '/journal-quotidien',
    path: '/journal-quotidien',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFournisseursRoute =
  AuthenticatedFournisseursRouteImport.update({
    id: '/fournisseurs',
    path: '/fournisseurs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacturesRoute = AuthenticatedFacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepensesRoute = AuthenticatedDepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursOrRoute = AuthenticatedCoursOrRouteImport.update({
  id: '/cours-or',
  path: '/cours-or',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoutiqueRoute = AuthenticatedBoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProduitIdRoute = AuthenticatedProduitIdRouteImport.update({
  id: '/produit/$id',
  path: '/produit/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFournisseursIdRoute =
  AuthenticatedFournisseursIdRouteImport.update({
    id: '/fournisseurs_/$id',
    path: '/fournisseurs/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients_/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksUpdateGoldPricesRoute =
  ApiPublicHooksUpdateGoldPricesRouteImport.update({
    id: '/api/public/hooks/update-gold-prices',
    path: '/api/public/hooks/update-gold-prices',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acces': typeof AccesRoute
  '/activation': typeof ActivationRoute
  '/auth': typeof AuthRoute
  '/create-account': typeof CreateAccountRoute
  '/demo': typeof DemoRouteWithChildren
  '/owner': typeof OwnerRoute
  '/super-admin-access': typeof SuperAdminAccessRoute
  '/boutique': typeof AuthenticatedBoutiqueRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/cours-or': typeof AuthenticatedCoursOrRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/depenses': typeof AuthenticatedDepensesRoute
  '/factures': typeof AuthenticatedFacturesRoute
  '/fournisseurs': typeof AuthenticatedFournisseursRoute
  '/journal-quotidien': typeof AuthenticatedJournalQuotidienRoute
  '/nouvelle-vente': typeof AuthenticatedNouvelleVenteRoute
  '/or-casse': typeof AuthenticatedOrCasseRoute
  '/paiements-en-attente': typeof AuthenticatedPaiementsEnAttenteRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/parures': typeof AuthenticatedParuresRoute
  '/reparations': typeof AuthenticatedReparationsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/demo/clients': typeof DemoClientsRoute
  '/demo/cours-or': typeof DemoCoursOrRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/depenses': typeof DemoDepensesRoute
  '/demo/factures': typeof DemoFacturesRoute
  '/demo/fournisseurs': typeof DemoFournisseursRoute
  '/demo/journal-quotidien': typeof DemoJournalQuotidienRoute
  '/demo/or-casse': typeof DemoOrCasseRoute
  '/demo/paiements-en-attente': typeof DemoPaiementsEnAttenteRoute
  '/demo/parures': typeof DemoParuresRoute
  '/demo/reparations': typeof DemoReparationsRoute
  '/demo/stock': typeof DemoStockRoute
  '/invite/$code': typeof InviteCodeRoute
  '/suivi/$token': typeof SuiviTokenRoute
  '/demo/': typeof DemoIndexRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/fournisseurs/$id': typeof AuthenticatedFournisseursIdRoute
  '/produit/$id': typeof AuthenticatedProduitIdRoute
  '/api/public/hooks/update-gold-prices': typeof ApiPublicHooksUpdateGoldPricesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acces': typeof AccesRoute
  '/activation': typeof ActivationRoute
  '/auth': typeof AuthRoute
  '/create-account': typeof CreateAccountRoute
  '/owner': typeof OwnerRoute
  '/super-admin-access': typeof SuperAdminAccessRoute
  '/boutique': typeof AuthenticatedBoutiqueRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/cours-or': typeof AuthenticatedCoursOrRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/depenses': typeof AuthenticatedDepensesRoute
  '/factures': typeof AuthenticatedFacturesRoute
  '/fournisseurs': typeof AuthenticatedFournisseursRoute
  '/journal-quotidien': typeof AuthenticatedJournalQuotidienRoute
  '/nouvelle-vente': typeof AuthenticatedNouvelleVenteRoute
  '/or-casse': typeof AuthenticatedOrCasseRoute
  '/paiements-en-attente': typeof AuthenticatedPaiementsEnAttenteRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/parures': typeof AuthenticatedParuresRoute
  '/reparations': typeof AuthenticatedReparationsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/demo/clients': typeof DemoClientsRoute
  '/demo/cours-or': typeof DemoCoursOrRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/depenses': typeof DemoDepensesRoute
  '/demo/factures': typeof DemoFacturesRoute
  '/demo/fournisseurs': typeof DemoFournisseursRoute
  '/demo/journal-quotidien': typeof DemoJournalQuotidienRoute
  '/demo/or-casse': typeof DemoOrCasseRoute
  '/demo/paiements-en-attente': typeof DemoPaiementsEnAttenteRoute
  '/demo/parures': typeof DemoParuresRoute
  '/demo/reparations': typeof DemoReparationsRoute
  '/demo/stock': typeof DemoStockRoute
  '/invite/$code': typeof InviteCodeRoute
  '/suivi/$token': typeof SuiviTokenRoute
  '/demo': typeof DemoIndexRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/fournisseurs/$id': typeof AuthenticatedFournisseursIdRoute
  '/produit/$id': typeof AuthenticatedProduitIdRoute
  '/api/public/hooks/update-gold-prices': typeof ApiPublicHooksUpdateGoldPricesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acces': typeof AccesRoute
  '/activation': typeof ActivationRoute
  '/auth': typeof AuthRoute
  '/create-account': typeof CreateAccountRoute
  '/demo': typeof DemoRouteWithChildren
  '/owner': typeof OwnerRoute
  '/super-admin-access': typeof SuperAdminAccessRoute
  '/_authenticated/boutique': typeof AuthenticatedBoutiqueRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/cours-or': typeof AuthenticatedCoursOrRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/depenses': typeof AuthenticatedDepensesRoute
  '/_authenticated/factures': typeof AuthenticatedFacturesRoute
  '/_authenticated/fournisseurs': typeof AuthenticatedFournisseursRoute
  '/_authenticated/journal-quotidien': typeof AuthenticatedJournalQuotidienRoute
  '/_authenticated/nouvelle-vente': typeof AuthenticatedNouvelleVenteRoute
  '/_authenticated/or-casse': typeof AuthenticatedOrCasseRoute
  '/_authenticated/paiements-en-attente': typeof AuthenticatedPaiementsEnAttenteRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/parures': typeof AuthenticatedParuresRoute
  '/_authenticated/reparations': typeof AuthenticatedReparationsRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRoute
  '/demo/clients': typeof DemoClientsRoute
  '/demo/cours-or': typeof DemoCoursOrRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/depenses': typeof DemoDepensesRoute
  '/demo/factures': typeof DemoFacturesRoute
  '/demo/fournisseurs': typeof DemoFournisseursRoute
  '/demo/journal-quotidien': typeof DemoJournalQuotidienRoute
  '/demo/or-casse': typeof DemoOrCasseRoute
  '/demo/paiements-en-attente': typeof DemoPaiementsEnAttenteRoute
  '/demo/parures': typeof DemoParuresRoute
  '/demo/reparations': typeof DemoReparationsRoute
  '/demo/stock': typeof DemoStockRoute
  '/invite/$code': typeof InviteCodeRoute
  '/suivi/$token': typeof SuiviTokenRoute
  '/demo/': typeof DemoIndexRoute
  '/_authenticated/clients_/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/fournisseurs_/$id': typeof AuthenticatedFournisseursIdRoute
  '/_authenticated/produit/$id': typeof AuthenticatedProduitIdRoute
  '/api/public/hooks/update-gold-prices': typeof ApiPublicHooksUpdateGoldPricesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acces'
    | '/activation'
    | '/auth'
    | '/create-account'
    | '/demo'
    | '/owner'
    | '/super-admin-access'
    | '/boutique'
    | '/clients'
    | '/cours-or'
    | '/dashboard'
    | '/depenses'
    | '/factures'
    | '/fournisseurs'
    | '/journal-quotidien'
    | '/nouvelle-vente'
    | '/or-casse'
    | '/paiements-en-attente'
    | '/parametres'
    | '/parures'
    | '/reparations'
    | '/stock'
    | '/super-admin'
    | '/demo/clients'
    | '/demo/cours-or'
    | '/demo/dashboard'
    | '/demo/depenses'
    | '/demo/factures'
    | '/demo/fournisseurs'
    | '/demo/journal-quotidien'
    | '/demo/or-casse'
    | '/demo/paiements-en-attente'
    | '/demo/parures'
    | '/demo/reparations'
    | '/demo/stock'
    | '/invite/$code'
    | '/suivi/$token'
    | '/demo/'
    | '/clients/$id'
    | '/fournisseurs/$id'
    | '/produit/$id'
    | '/api/public/hooks/update-gold-prices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acces'
    | '/activation'
    | '/auth'
    | '/create-account'
    | '/owner'
    | '/super-admin-access'
    | '/boutique'
    | '/clients'
    | '/cours-or'
    | '/dashboard'
    | '/depenses'
    | '/factures'
    | '/fournisseurs'
    | '/journal-quotidien'
    | '/nouvelle-vente'
    | '/or-casse'
    | '/paiements-en-attente'
    | '/parametres'
    | '/parures'
    | '/reparations'
    | '/stock'
    | '/super-admin'
    | '/demo/clients'
    | '/demo/cours-or'
    | '/demo/dashboard'
    | '/demo/depenses'
    | '/demo/factures'
    | '/demo/fournisseurs'
    | '/demo/journal-quotidien'
    | '/demo/or-casse'
    | '/demo/paiements-en-attente'
    | '/demo/parures'
    | '/demo/reparations'
    | '/demo/stock'
    | '/invite/$code'
    | '/suivi/$token'
    | '/demo'
    | '/clients/$id'
    | '/fournisseurs/$id'
    | '/produit/$id'
    | '/api/public/hooks/update-gold-prices'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acces'
    | '/activation'
    | '/auth'
    | '/create-account'
    | '/demo'
    | '/owner'
    | '/super-admin-access'
    | '/_authenticated/boutique'
    | '/_authenticated/clients'
    | '/_authenticated/cours-or'
    | '/_authenticated/dashboard'
    | '/_authenticated/depenses'
    | '/_authenticated/factures'
    | '/_authenticated/fournisseurs'
    | '/_authenticated/journal-quotidien'
    | '/_authenticated/nouvelle-vente'
    | '/_authenticated/or-casse'
    | '/_authenticated/paiements-en-attente'
    | '/_authenticated/parametres'
    | '/_authenticated/parures'
    | '/_authenticated/reparations'
    | '/_authenticated/stock'
    | '/_authenticated/super-admin'
    | '/demo/clients'
    | '/demo/cours-or'
    | '/demo/dashboard'
    | '/demo/depenses'
    | '/demo/factures'
    | '/demo/fournisseurs'
    | '/demo/journal-quotidien'
    | '/demo/or-casse'
    | '/demo/paiements-en-attente'
    | '/demo/parures'
    | '/demo/reparations'
    | '/demo/stock'
    | '/invite/$code'
    | '/suivi/$token'
    | '/demo/'
    | '/_authenticated/clients_/$id'
    | '/_authenticated/fournisseurs_/$id'
    | '/_authenticated/produit/$id'
    | '/api/public/hooks/update-gold-prices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccesRoute: typeof AccesRoute
  ActivationRoute: typeof ActivationRoute
  AuthRoute: typeof AuthRoute
  CreateAccountRoute: typeof CreateAccountRoute
  DemoRoute: typeof DemoRouteWithChildren
  OwnerRoute: typeof OwnerRoute
  SuperAdminAccessRoute: typeof SuperAdminAccessRoute
  InviteCodeRoute: typeof InviteCodeRoute
  SuiviTokenRoute: typeof SuiviTokenRoute
  ApiPublicHooksUpdateGoldPricesRoute: typeof ApiPublicHooksUpdateGoldPricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin-access': {
      id: '/super-admin-access'
      path: '/super-admin-access'
      fullPath: '/super-admin-access'
      preLoaderRoute: typeof SuperAdminAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation': {
      id: '/activation'
      path: '/activation'
      fullPath: '/activation'
      preLoaderRoute: typeof ActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acces': {
      id: '/acces'
      path: '/acces'
      fullPath: '/acces'
      preLoaderRoute: typeof AccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/suivi/$token': {
      id: '/suivi/$token'
      path: '/suivi/$token'
      fullPath: '/suivi/$token'
      preLoaderRoute: typeof SuiviTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/stock': {
      id: '/demo/stock'
      path: '/stock'
      fullPath: '/demo/stock'
      preLoaderRoute: typeof DemoStockRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/reparations': {
      id: '/demo/reparations'
      path: '/reparations'
      fullPath: '/demo/reparations'
      preLoaderRoute: typeof DemoReparationsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/parures': {
      id: '/demo/parures'
      path: '/parures'
      fullPath: '/demo/parures'
      preLoaderRoute: typeof DemoParuresRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/paiements-en-attente': {
      id: '/demo/paiements-en-attente'
      path: '/paiements-en-attente'
      fullPath: '/demo/paiements-en-attente'
      preLoaderRoute: typeof DemoPaiementsEnAttenteRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/or-casse': {
      id: '/demo/or-casse'
      path: '/or-casse'
      fullPath: '/demo/or-casse'
      preLoaderRoute: typeof DemoOrCasseRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/journal-quotidien': {
      id: '/demo/journal-quotidien'
      path: '/journal-quotidien'
      fullPath: '/demo/journal-quotidien'
      preLoaderRoute: typeof DemoJournalQuotidienRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/fournisseurs': {
      id: '/demo/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/demo/fournisseurs'
      preLoaderRoute: typeof DemoFournisseursRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/factures': {
      id: '/demo/factures'
      path: '/factures'
      fullPath: '/demo/factures'
      preLoaderRoute: typeof DemoFacturesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/depenses': {
      id: '/demo/depenses'
      path: '/depenses'
      fullPath: '/demo/depenses'
      preLoaderRoute: typeof DemoDepensesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/dashboard': {
      id: '/demo/dashboard'
      path: '/dashboard'
      fullPath: '/demo/dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/cours-or': {
      id: '/demo/cours-or'
      path: '/cours-or'
      fullPath: '/demo/cours-or'
      preLoaderRoute: typeof DemoCoursOrRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/clients': {
      id: '/demo/clients'
      path: '/clients'
      fullPath: '/demo/clients'
      preLoaderRoute: typeof DemoClientsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reparations': {
      id: '/_authenticated/reparations'
      path: '/reparations'
      fullPath: '/reparations'
      preLoaderRoute: typeof AuthenticatedReparationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parures': {
      id: '/_authenticated/parures'
      path: '/parures'
      fullPath: '/parures'
      preLoaderRoute: typeof AuthenticatedParuresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paiements-en-attente': {
      id: '/_authenticated/paiements-en-attente'
      path: '/paiements-en-attente'
      fullPath: '/paiements-en-attente'
      preLoaderRoute: typeof AuthenticatedPaiementsEnAttenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/or-casse': {
      id: '/_authenticated/or-casse'
      path: '/or-casse'
      fullPath: '/or-casse'
      preLoaderRoute: typeof AuthenticatedOrCasseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nouvelle-vente': {
      id: '/_authenticated/nouvelle-vente'
      path: '/nouvelle-vente'
      fullPath: '/nouvelle-vente'
      preLoaderRoute: typeof AuthenticatedNouvelleVenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal-quotidien': {
      id: '/_authenticated/journal-quotidien'
      path: '/journal-quotidien'
      fullPath: '/journal-quotidien'
      preLoaderRoute: typeof AuthenticatedJournalQuotidienRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fournisseurs': {
      id: '/_authenticated/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof AuthenticatedFournisseursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/factures': {
      id: '/_authenticated/factures'
      path: '/factures'
      fullPath: '/factures'
      preLoaderRoute: typeof AuthenticatedFacturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depenses': {
      id: '/_authenticated/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof AuthenticatedDepensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cours-or': {
      id: '/_authenticated/cours-or'
      path: '/cours-or'
      fullPath: '/cours-or'
      preLoaderRoute: typeof AuthenticatedCoursOrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boutique': {
      id: '/_authenticated/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof AuthenticatedBoutiqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produit/$id': {
      id: '/_authenticated/produit/$id'
      path: '/produit/$id'
      fullPath: '/produit/$id'
      preLoaderRoute: typeof AuthenticatedProduitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fournisseurs_/$id': {
      id: '/_authenticated/fournisseurs_/$id'
      path: '/fournisseurs/$id'
      fullPath: '/fournisseurs/$id'
      preLoaderRoute: typeof AuthenticatedFournisseursIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients_/$id': {
      id: '/_authenticated/clients_/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/update-gold-prices': {
      id: '/api/public/hooks/update-gold-prices'
      path: '/api/public/hooks/update-gold-prices'
      fullPath: '/api/public/hooks/update-gold-prices'
      preLoaderRoute: typeof ApiPublicHooksUpdateGoldPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBoutiqueRoute: typeof AuthenticatedBoutiqueRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedCoursOrRoute: typeof AuthenticatedCoursOrRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepensesRoute: typeof AuthenticatedDepensesRoute
  AuthenticatedFacturesRoute: typeof AuthenticatedFacturesRoute
  AuthenticatedFournisseursRoute: typeof AuthenticatedFournisseursRoute
  AuthenticatedJournalQuotidienRoute: typeof AuthenticatedJournalQuotidienRoute
  AuthenticatedNouvelleVenteRoute: typeof AuthenticatedNouvelleVenteRoute
  AuthenticatedOrCasseRoute: typeof AuthenticatedOrCasseRoute
  AuthenticatedPaiementsEnAttenteRoute: typeof AuthenticatedPaiementsEnAttenteRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedParuresRoute: typeof AuthenticatedParuresRoute
  AuthenticatedReparationsRoute: typeof AuthenticatedReparationsRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRoute
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedFournisseursIdRoute: typeof AuthenticatedFournisseursIdRoute
  AuthenticatedProduitIdRoute: typeof AuthenticatedProduitIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBoutiqueRoute: AuthenticatedBoutiqueRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedCoursOrRoute: AuthenticatedCoursOrRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepensesRoute: AuthenticatedDepensesRoute,
  AuthenticatedFacturesRoute: AuthenticatedFacturesRoute,
  AuthenticatedFournisseursRoute: AuthenticatedFournisseursRoute,
  AuthenticatedJournalQuotidienRoute: AuthenticatedJournalQuotidienRoute,
  AuthenticatedNouvelleVenteRoute: AuthenticatedNouvelleVenteRoute,
  AuthenticatedOrCasseRoute: AuthenticatedOrCasseRoute,
  AuthenticatedPaiementsEnAttenteRoute: AuthenticatedPaiementsEnAttenteRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedParuresRoute: AuthenticatedParuresRoute,
  AuthenticatedReparationsRoute: AuthenticatedReparationsRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRoute,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedFournisseursIdRoute: AuthenticatedFournisseursIdRoute,
  AuthenticatedProduitIdRoute: AuthenticatedProduitIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DemoRouteChildren {
  DemoClientsRoute: typeof DemoClientsRoute
  DemoCoursOrRoute: typeof DemoCoursOrRoute
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoDepensesRoute: typeof DemoDepensesRoute
  DemoFacturesRoute: typeof DemoFacturesRoute
  DemoFournisseursRoute: typeof DemoFournisseursRoute
  DemoJournalQuotidienRoute: typeof DemoJournalQuotidienRoute
  DemoOrCasseRoute: typeof DemoOrCasseRoute
  DemoPaiementsEnAttenteRoute: typeof DemoPaiementsEnAttenteRoute
  DemoParuresRoute: typeof DemoParuresRoute
  DemoReparationsRoute: typeof DemoReparationsRoute
  DemoStockRoute: typeof DemoStockRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoClientsRoute: DemoClientsRoute,
  DemoCoursOrRoute: DemoCoursOrRoute,
  DemoDashboardRoute: DemoDashboardRoute,
  DemoDepensesRoute: DemoDepensesRoute,
  DemoFacturesRoute: DemoFacturesRoute,
  DemoFournisseursRoute: DemoFournisseursRoute,
  DemoJournalQuotidienRoute: DemoJournalQuotidienRoute,
  DemoOrCasseRoute: DemoOrCasseRoute,
  DemoPaiementsEnAttenteRoute: DemoPaiementsEnAttenteRoute,
  DemoParuresRoute: DemoParuresRoute,
  DemoReparationsRoute: DemoReparationsRoute,
  DemoStockRoute: DemoStockRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccesRoute: AccesRoute,
  ActivationRoute: ActivationRoute,
  AuthRoute: AuthRoute,
  CreateAccountRoute: CreateAccountRoute,
  DemoRoute: DemoRouteWithChildren,
  OwnerRoute: OwnerRoute,
  SuperAdminAccessRoute: SuperAdminAccessRoute,
  InviteCodeRoute: InviteCodeRoute,
  SuiviTokenRoute: SuiviTokenRoute,
  ApiPublicHooksUpdateGoldPricesRoute: ApiPublicHooksUpdateGoldPricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
