/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedPaiementsEnAttenteRouteImport } from './routes/_authenticated/paiements-en-attente'
import { Route as AuthenticatedNouvelleVenteRouteImport } from './routes/_authenticated/nouvelle-vente'
import { Route as AuthenticatedFournisseursRouteImport } from './routes/_authenticated/fournisseurs'
import { Route as AuthenticatedFacturesRouteImport } from './routes/_authenticated/factures'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoursOrRouteImport } from './routes/_authenticated/cours-or'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedProduitIdRouteImport } from './routes/_authenticated/produit.$id'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients_.$id'
import { Route as ApiPublicHooksUpdateGoldPricesRouteImport } from './routes/api/public/hooks/update-gold-prices'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaiementsEnAttenteRoute =
  AuthenticatedPaiementsEnAttenteRouteImport.update({
    id: '/paiements-en-attente',
    path: '/paiements-en-attente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNouvelleVenteRoute =
  AuthenticatedNouvelleVenteRouteImport.update({
    id: '/nouvelle-vente',
    path: '/nouvelle-vente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFournisseursRoute =
  AuthenticatedFournisseursRouteImport.update({
    id: '/fournisseurs',
    path: '/fournisseurs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacturesRoute = AuthenticatedFacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursOrRoute = AuthenticatedCoursOrRouteImport.update({
  id: '/cours-or',
  path: '/cours-or',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProduitIdRoute = AuthenticatedProduitIdRouteImport.update({
  id: '/produit/$id',
  path: '/produit/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients_/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksUpdateGoldPricesRoute =
  ApiPublicHooksUpdateGoldPricesRouteImport.update({
    id: '/api/public/hooks/update-gold-prices',
    path: '/api/public/hooks/update-gold-prices',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/cours-or': typeof AuthenticatedCoursOrRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/factures': typeof AuthenticatedFacturesRoute
  '/fournisseurs': typeof AuthenticatedFournisseursRoute
  '/nouvelle-vente': typeof AuthenticatedNouvelleVenteRoute
  '/paiements-en-attente': typeof AuthenticatedPaiementsEnAttenteRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/stock': typeof AuthenticatedStockRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/produit/$id': typeof AuthenticatedProduitIdRoute
  '/api/public/hooks/update-gold-prices': typeof ApiPublicHooksUpdateGoldPricesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/cours-or': typeof AuthenticatedCoursOrRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/factures': typeof AuthenticatedFacturesRoute
  '/fournisseurs': typeof AuthenticatedFournisseursRoute
  '/nouvelle-vente': typeof AuthenticatedNouvelleVenteRoute
  '/paiements-en-attente': typeof AuthenticatedPaiementsEnAttenteRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/stock': typeof AuthenticatedStockRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/produit/$id': typeof AuthenticatedProduitIdRoute
  '/api/public/hooks/update-gold-prices': typeof ApiPublicHooksUpdateGoldPricesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/cours-or': typeof AuthenticatedCoursOrRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/factures': typeof AuthenticatedFacturesRoute
  '/_authenticated/fournisseurs': typeof AuthenticatedFournisseursRoute
  '/_authenticated/nouvelle-vente': typeof AuthenticatedNouvelleVenteRoute
  '/_authenticated/paiements-en-attente': typeof AuthenticatedPaiementsEnAttenteRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/clients_/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/produit/$id': typeof AuthenticatedProduitIdRoute
  '/api/public/hooks/update-gold-prices': typeof ApiPublicHooksUpdateGoldPricesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clients'
    | '/cours-or'
    | '/dashboard'
    | '/factures'
    | '/fournisseurs'
    | '/nouvelle-vente'
    | '/paiements-en-attente'
    | '/parametres'
    | '/stock'
    | '/clients/$id'
    | '/produit/$id'
    | '/api/public/hooks/update-gold-prices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clients'
    | '/cours-or'
    | '/dashboard'
    | '/factures'
    | '/fournisseurs'
    | '/nouvelle-vente'
    | '/paiements-en-attente'
    | '/parametres'
    | '/stock'
    | '/clients/$id'
    | '/produit/$id'
    | '/api/public/hooks/update-gold-prices'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clients'
    | '/_authenticated/cours-or'
    | '/_authenticated/dashboard'
    | '/_authenticated/factures'
    | '/_authenticated/fournisseurs'
    | '/_authenticated/nouvelle-vente'
    | '/_authenticated/paiements-en-attente'
    | '/_authenticated/parametres'
    | '/_authenticated/stock'
    | '/_authenticated/clients_/$id'
    | '/_authenticated/produit/$id'
    | '/api/public/hooks/update-gold-prices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksUpdateGoldPricesRoute: typeof ApiPublicHooksUpdateGoldPricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paiements-en-attente': {
      id: '/_authenticated/paiements-en-attente'
      path: '/paiements-en-attente'
      fullPath: '/paiements-en-attente'
      preLoaderRoute: typeof AuthenticatedPaiementsEnAttenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nouvelle-vente': {
      id: '/_authenticated/nouvelle-vente'
      path: '/nouvelle-vente'
      fullPath: '/nouvelle-vente'
      preLoaderRoute: typeof AuthenticatedNouvelleVenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fournisseurs': {
      id: '/_authenticated/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof AuthenticatedFournisseursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/factures': {
      id: '/_authenticated/factures'
      path: '/factures'
      fullPath: '/factures'
      preLoaderRoute: typeof AuthenticatedFacturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cours-or': {
      id: '/_authenticated/cours-or'
      path: '/cours-or'
      fullPath: '/cours-or'
      preLoaderRoute: typeof AuthenticatedCoursOrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produit/$id': {
      id: '/_authenticated/produit/$id'
      path: '/produit/$id'
      fullPath: '/produit/$id'
      preLoaderRoute: typeof AuthenticatedProduitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients_/$id': {
      id: '/_authenticated/clients_/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/update-gold-prices': {
      id: '/api/public/hooks/update-gold-prices'
      path: '/api/public/hooks/update-gold-prices'
      fullPath: '/api/public/hooks/update-gold-prices'
      preLoaderRoute: typeof ApiPublicHooksUpdateGoldPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedCoursOrRoute: typeof AuthenticatedCoursOrRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFacturesRoute: typeof AuthenticatedFacturesRoute
  AuthenticatedFournisseursRoute: typeof AuthenticatedFournisseursRoute
  AuthenticatedNouvelleVenteRoute: typeof AuthenticatedNouvelleVenteRoute
  AuthenticatedPaiementsEnAttenteRoute: typeof AuthenticatedPaiementsEnAttenteRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedProduitIdRoute: typeof AuthenticatedProduitIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedCoursOrRoute: AuthenticatedCoursOrRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFacturesRoute: AuthenticatedFacturesRoute,
  AuthenticatedFournisseursRoute: AuthenticatedFournisseursRoute,
  AuthenticatedNouvelleVenteRoute: AuthenticatedNouvelleVenteRoute,
  AuthenticatedPaiementsEnAttenteRoute: AuthenticatedPaiementsEnAttenteRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedProduitIdRoute: AuthenticatedProduitIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksUpdateGoldPricesRoute: ApiPublicHooksUpdateGoldPricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
